// <auto-generated />
namespace coinpanic_airdrop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddLnNodeChannel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLnNodeChannel));
        
        string IMigrationMetadata.Id
        {
            get { return "201804100208207_AddLnNodeChannel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
